### ISSUE TITLE
Error: "Could not find 'defaultsc' scoreboard"

### ISSUE THREAD

**Issue by MaxwellRose101** [Xitee1/PowerBoard#30]
So, basically, when I load up my server, an error message from PowerBoard shows up in the logs. It tells me that it could not find defaultsc.yml even though there is literally a defaultsc.yml. The tab-list and ranking system is working perfectly fine though. Why is this? Please help me ASAP.

**Comment by Xitee1** [comment]
By default there is no "defaultsc.yml". I don't know exactly because I don't have your config.yml but I think you could have changed the scoreboard-name of the default scoreboard to "defaultsc" for some reason. Then you have to make sure that this file exists in the /PowerBoard/scoreboards folder and has the config of a scoreboard in it.
