### ISSUE TITLE
Player Suffix not updating properly

### ISSUE THREAD

**Issue by Liathers** [Xitee1/PowerBoard#31]
When I set a player suffix to contain a placeholder, for example XP level, it doesn't update for anyone unless they disconnect and rejoin the server. It updates within chat, but not within the tab menu and their username, that is above the player.

Is this intentional behaviour, or is this something that can be resolved?
Thanks!

**Comment by Xitee1** [comment]
This is intentional. It is very performance intensive to update all ranks since the plugin needs to go a lot of loops to do so.
That's why by default it only updates after a rejoin. You can however define a update interval (ranks.update-interval) for example to 1 (one minute). It is also possibly to execute '/pb reload' or if possible by an self-written plugin on your server which calls the PB API to update the rank.
